In [ ]:
print("hello world")


hello world


In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
scalar=torch.tensor(2)

In [ ]:
scalar

tensor(2)

In [ ]:
scalar.ndim
scalar.shape

torch.Size([])

In [ ]:
scalar.item()

2

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[11,12,0],[1,2,0],[2,3,0]])
matrix

tensor([[11, 12,  0],
        [ 1,  2,  0],
        [ 2,  3,  0]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

3

In [ ]:
tensor1=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor1.shape

torch.Size([2, 3, 3])

In [ ]:
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor[0][0][0].item()

1

In [ ]:
random_tensor1=torch.rand(size=(1,3,3),dtype=torch.float64)
random_tensor1

tensor([[[0.3634, 0.3289, 0.9624],
         [0.0465, 0.6059, 0.8708],
         [0.0119, 0.3419, 0.6731]]], dtype=torch.float64)

In [ ]:
random_tensor1.dtype

torch.float64

In [ ]:
random_tensor2=torch.randint(0,10,size=(3,3),dtype=torch.int32)

In [ ]:
random_tensor2


tensor([[2, 6, 1],
        [9, 9, 1],
        [7, 5, 8]], dtype=torch.int32)

In [ ]:
torch.rand(1,3,3)

tensor([[[0.1251, 0.9680, 0.0428],
         [0.7844, 0.7551, 0.3633],
         [0.9314, 0.3854, 0.6127]]])

In [ ]:
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones=torch.ones((3,3),dtype=torch.int32)
ones

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
ones.dtype

torch.int32

In [ ]:
torch.arange(5,10)

tensor([5, 6, 7, 8, 9])

In [ ]:
torch.arange(1,1000,69)

tensor([  1,  70, 139, 208, 277, 346, 415, 484, 553, 622, 691, 760, 829, 898,
        967])

In [ ]:
zeros_like=torch.zeros_like(input=random_tensor1)
zeros_like

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [ ]:
float_16=torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
float_16

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
float_32=torch.tensor([1,2,3],dtype=torch.float32)
float_32

tensor([1., 2., 3.])

In [ ]:
float_16*float_32

tensor([1., 4., 9.])

In [ ]:
random_tensor3=torch.rand((3,4),dtype=torch.float64)
random_tensor3

tensor([[0.7406, 0.7616, 0.2964, 0.4751],
        [0.0807, 0.2976, 0.9797, 0.3207],
        [0.3660, 0.7969, 0.6826, 0.1615]], dtype=torch.float64)

In [ ]:
print(f"Datatype of the tensor: {random_tensor3.dtype}")
print(f"Shape of the tensor: {random_tensor3.shape}")
print(f"Device of the tensor: {random_tensor3.device}")

Datatype of the tensor: torch.float64
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


In [ ]:


# Check if GPU (CUDA) is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


Using device: cuda


In [ ]:
random_image_size_tensor = torch.rand(size=(3, 3, 3))
random_image_size_tensor, random_image_size_tensor.type

(tensor([[[0.0405, 0.7282, 0.2237],
          [0.2545, 0.2182, 0.7496],
          [0.2580, 0.4332, 0.6893]],
 
         [[0.4250, 0.5671, 0.0432],
          [0.1199, 0.7845, 0.5123],
          [0.6295, 0.4558, 0.5543]],
 
         [[0.9241, 0.4004, 0.7306],
          [0.1273, 0.1810, 0.4165],
          [0.1849, 0.0380, 0.0874]]]),
 <function Tensor.type>)

In [ ]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([2.0, 3.0], requires_grad=True)

# Some operation
y = x * x + 2

# Sum the result to get a scalar
z = y.sum()

# Compute gradients
z.backward()

# Now x.grad contains the derivative of z with respect to x
print(x.grad)


tensor([4., 6.])


In [ ]:
tensor10 = torch.tensor([1,2,3])
tensor10 * 10
tensor10.ndim

1

In [ ]:
torch.multiply(tensor10,100)

tensor([100, 200, 300])

In [ ]:
tensor10 * tensor10

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor10,tensor10)

tensor(14)

In [ ]:
t1=torch.rand(2,3)
t2=torch.rand(3,2)
t3=torch.mm(t1,t2)
t3

tensor([[0.2959, 0.4280],
        [0.5452, 0.7770]])

In [ ]:
t2.T

tensor([[0.0712, 0.3008, 0.5367],
        [0.2477, 0.4552, 0.5256]])

In [ ]:
torch.mm(t1,t1.T)

tensor([[0.4416, 0.6959],
        [0.6959, 1.3004]])

In [ ]:
x=torch.arange(12,121,12)
x

tensor([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120])

In [ ]:
x.min()

tensor(12)

In [ ]:
x.max()

tensor(120)

In [ ]:
x.mean(dtype=torch.float32)

tensor(66.)

In [ ]:
torch.min(x),torch.max(x)

(tensor(12), tensor(120))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(66.)

In [ ]:
x, x.dtype

(tensor([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120]), torch.int64)

In [ ]:
torch.sum(x)

tensor(660)

In [ ]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [ ]:
torch.argmin(x),torch.argmax(x)

(tensor(0), tensor(9))

In [ ]:
torch.cuda.is_available()

True

In [ ]:
x = torch.arange(1,9)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [ ]:
x_reshaped= x.reshape(1,8)
x_reshaped ,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [ ]:
z=x.view(1,8)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
z[:,1]=100
x,z

(tensor([  1, 100,   3,   4,   5,   6,   7,   8]),
 tensor([[  1, 100,   3,   4,   5,   6,   7,   8]]))

In [ ]:
x_stacked=torch.stack([x,x,x],dim=1)
x_stacked,x_stacked.shape

(tensor([[  1,   1,   1],
         [100, 100, 100],
         [  3,   3,   3],
         [  4,   4,   4],
         [  5,   5,   5],
         [  6,   6,   6],
         [  7,   7,   7],
         [  8,   8,   8]]),
 torch.Size([8, 3]))

In [ ]:
torch.reshape(x_stacked,(3,8))

tensor([[  1,   1,   1, 100, 100, 100,   3,   3],
        [  3,   4,   4,   4,   5,   5,   5,   6],
        [  6,   6,   7,   7,   7,   8,   8,   8]])

In [ ]:

x_stacked

tensor([[  1,   1,   1],
        [100, 100, 100],
        [  3,   3,   3],
        [  4,   4,   4],
        [  5,   5,   5],
        [  6,   6,   6],
        [  7,   7,   7],
        [  8,   8,   8]])

In [ ]:
x_squeezed= torch.squeeze(x_reshaped)
x_squeezed,x_squeezed.shape

(tensor([  1, 100,   3,   4,   5,   6,   7,   8]), torch.Size([8]))

In [69]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[  1, 100,   3,   4,   5,   6,   7,   8]]), torch.Size([1, 8]))

In [ ]:
z=torch.rand(3,4,5)
z

tensor([[[0.0912, 0.4991, 0.1455, 0.3482, 0.8030],
         [0.6578, 0.4173, 0.4488, 0.8876, 0.2386],
         [0.3363, 0.6057, 0.0040, 0.9965, 0.3565],
         [0.5164, 0.4967, 0.6862, 0.2362, 0.8575]],

        [[0.7705, 0.8084, 0.4115, 0.0319, 0.4589],
         [0.9240, 0.4444, 0.2583, 0.1305, 0.2006],
         [0.4465, 0.9328, 0.3570, 0.2864, 0.0269],
         [0.7828, 0.4026, 0.6118, 0.0269, 0.9545]],

        [[0.9265, 0.9363, 0.4391, 0.5198, 0.3466],
         [0.2481, 0.6621, 0.5597, 0.8524, 0.6715],
         [0.3182, 0.0166, 0.2267, 0.4657, 0.1218],
         [0.4001, 0.3354, 0.4172, 0.0659, 0.2193]]])

In [ ]:
z_permuted=z.permute(1,2,0)
z_permuted,z_permuted.shape




(tensor([[[0.0912, 0.7705, 0.9265],
          [0.4991, 0.8084, 0.9363],
          [0.1455, 0.4115, 0.4391],
          [0.3482, 0.0319, 0.5198],
          [0.8030, 0.4589, 0.3466]],
 
         [[0.6578, 0.9240, 0.2481],
          [0.4173, 0.4444, 0.6621],
          [0.4488, 0.2583, 0.5597],
          [0.8876, 0.1305, 0.8524],
          [0.2386, 0.2006, 0.6715]],
 
         [[0.3363, 0.4465, 0.3182],
          [0.6057, 0.9328, 0.0166],
          [0.0040, 0.3570, 0.2267],
          [0.9965, 0.2864, 0.4657],
          [0.3565, 0.0269, 0.1218]],
 
         [[0.5164, 0.7828, 0.4001],
          [0.4967, 0.4026, 0.3354],
          [0.6862, 0.6118, 0.4172],
          [0.2362, 0.0269, 0.0659],
          [0.8575, 0.9545, 0.2193]]]),
 torch.Size([4, 5, 3]))

In [70]:
torch.tenosr()

AttributeError: module 'torch' has no attribute 'tenosr'